### ISSUE TITLE
Implement video data retrieval & saving

### ISSUE THREAD

**Issue by leingenm** [RomanMager/ypm#32]
### LINKS:
- [ER Diagram](https://drive.google.com/file/d/1ESsI9DQCrAjPEpK6wp-Z0cT65nF0uNyt/view?usp=sharing)

### TO-DO:
- [x] Define DB schema
- [x] Add dependency to manage DB migrations
- [x] Set up DB migrations
- [x] Add Entities representing DB tables
- [x] Set up proper connections between entities in JPA

### TO-DO:
- [x] Create controller
- [x] Implement a service layer that handles data saving
